# Adapted from https://github.com/actions/starter-workflows/blob/e9e00b017736d3b3811cedf1ee2e8ceb3c48e3dd/ci/npm-publish.yml
name: Deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pre_deploy:
    runs-on: ubuntu-latest
    name: Deploy
    permissions:
      # Permissions required for the changesets action
      # to be able to create a new branch and open a pull request
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        # Reference: https://github.com/changesets/changesets/issues/517#issuecomment-1182094769
        with:
          ref: ${{github.event.pull_request.head.sha}}
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - uses: pnpm/action-setup@v2.2.4
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: true
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
      - run: pnpm run build
      - name: Run Playwright tests
        run: pnpm exec playwright test
      - run: pnpm run changeset-status
      #- uses: actions/upload-artifact@v3
      #  if: always()
      #  with:
      #    name: playwright-report
      #    path: playwright-report/
      #    retention-days: 30